name = "lumin/teams"
version = "0.1.0"
license = "MIT"
private = true

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }

[dependencies]
framework = { name = "lumin/framework", version = "^11.0.0" }
debugger = { name = "lumin/debugger", version = "^1.0.3" }
vide = { wally = "centau/vide", version = "^0.3.1" }
colors = { wally = "gcaptn/tailwind-colors", version = "^0.1.6" }
toolbar = { wally = "stravant/create-shared-toolbar", version = "^0.1.0" }
ui_labs = { name = "pepeeltoro41/ui_labs", version = "^2.3.8" }
